/**
 * Adaptive RAG Engine — Query Routing, Vector Store, Retrieval Strategies,
 * Grounded Response Generation, Hallucination Guardrails & Citation System.
 */

import type { AppDocument } from "./app-data-context";

export type QueryIntent = "conceptual" | "factual" | "code" | "exam_prep" | "off_topic";
export type RetrievalStrategy = "Dense Vector" | "Hybrid (BM25+Dense)" | "Code Syntax Aware" | "Multi-Doc Synthesis" | "Direct Rejection";
export type RagMode = "Adaptive RAG (Auto)" | "Dense Vector" | "Hybrid (BM25+Dense)" | "Direct LLM";

export interface RetrievedChunk {
  id: string;
  docId: string;
  docName: string;
  fileType: string;
  subjectName: string;
  unit: string;
  pageNumber: number;
  content: string;
  similarityScore: number; // 0.0 to 1.0 (e.g. 0.88 = 88%)
  denseScore: number;
  bm25Score: number;
}

export interface PipelineStep {
  step: number;
  title: string;
  detail: string;
  status: "pending" | "running" | "completed";
}

export interface RagResponse {
  intent: QueryIntent;
  strategy: RetrievalStrategy;
  queryExpanded: string;
  retrievedChunks: RetrievedChunk[];
  confidenceScore: number; // 0 to 100
  hallucinationCheck: {
    passed: boolean;
    overlapScore: number; // 0.0 to 1.0
    reason: string;
  };
  answer: string;
  citations: Array<{
    id: string;
    docName: string;
    page: number;
    unit: string;
    chunkContent: string;
    similarity: number;
  }>;
  followUpSuggestions: string[];
  shouldEscalate: boolean;
  pipelineSteps: PipelineStep[];
}

// ─── Query Intent Classification ──────────────────────────────────────────────

export function classifyIntent(query: string): QueryIntent {
  const q = query.toLowerCase();

  // Off-topic check
  if (
    q.includes("movie") || q.includes("cricket") || q.includes("weather") ||
    q.includes("recipe") || q.includes("joke") || q.includes("who won") ||
    q.includes("president") || q.includes("capital of france")
  ) {
    return "off_topic";
  }

  // Code intent
  if (
    q.includes("code") || q.includes("python") || q.includes("function") ||
    q.includes("write a script") || q.includes("spark code") || q.includes("algorithm code") ||
    q.includes("class") || q.includes("syntax") || q.includes("implementation")
  ) {
    return "code";
  }

  // Exam prep intent
  if (
    q.includes("exam") || q.includes("important question") || q.includes("pyq") ||
    q.includes("syllabus") || q.includes("weightage") || q.includes("revision") ||
    q.includes("marks") || q.includes("previous year")
  ) {
    return "exam_prep";
  }

  // Factual intent
  if (
    q.includes("who created") || q.includes("when was") || q.includes("what year") ||
    q.includes("definition of") || q.includes("full form of") || q.includes("difference between") ||
    q.includes("vs") || q.includes("types of")
  ) {
    return "factual";
  }

  // Default conceptual
  return "conceptual";
}

export function selectStrategy(intent: QueryIntent, mode: RagMode): RetrievalStrategy {
  if (mode === "Direct LLM") return "Direct Rejection";
  if (mode === "Dense Vector") return "Dense Vector";
  if (mode === "Hybrid (BM25+Dense)") return "Hybrid (BM25+Dense)";

  switch (intent) {
    case "conceptual": return "Dense Vector";
    case "factual":    return "Hybrid (BM25+Dense)";
    case "code":       return "Code Syntax Aware";
    case "exam_prep":  return "Multi-Doc Synthesis";
    case "off_topic":  return "Direct Rejection";
  }
}

// ─── Chunking & Vector Simulation Engine ──────────────────────────────────────

const MOCK_CHUNKS: Record<string, string[]> = {
  "Big Data Analytics": [
    "MapReduce is a programming model and processing framework for distributed computing over large datasets. The execution consists of two primary functions: Map (which filters and transforms input key-value pairs) and Reduce (which aggregates intermediate results). Hadoop MapReduce handles fault tolerance by re-executing failed tasks on alternative worker nodes.",
    "The MapReduce Shuffle and Sort phase occurs between the Map and Reduce stages. Intermediate outputs generated by map tasks are partitioned by key, sorted locally, and transferred over the network to the respective reduce workers. Network congestion is mitigated using Combiner functions (mini-reducers on map nodes).",
    "Apache Spark replaces MapReduce's disk-heavy intermediate storage with in-memory Resilient Distributed Datasets (RDDs). Spark DataFrames provide schema optimization via the Catalyst Optimizer and Tungsten execution engine, yielding 10x-100x faster execution than MapReduce for iterative ML algorithms.",
    "HDFS (Hadoop Distributed File System) stores files as fixed-size blocks (typically 128MB). Each block is replicated (default factor = 3) across rack-separated DataNodes to ensure high availability. The NameNode manages file system metadata in RAM and tracks block locations.",
    "Stream processing frameworks like Apache Kafka and Apache Flink enable low-latency event processing. Kafka provides distributed log pub-sub with consumer groups, while Flink offers event-time processing with exactly-once state consistency guarantees.",
  ],
  "Machine Learning": [
    "Supervised learning algorithms infer a mathematical mapping function y = f(x) from labeled training data. Linear Regression models continuous outcomes using least-squares optimization, whereas Logistic Regression predicts class probabilities using the sigmoid function 1 / (1 + e^(-z)).",
    "The Bias-Variance Tradeoff quantifies model generalization error. High bias leads to underfitting (oversimplified models like linear fits on non-linear data). High variance leads to overfitting (complex models memorizing noise). Regularization (L1 Lasso, L2 Ridge) constrains weight magnitude to balance the tradeoff.",
    "Decision Trees split features based on Information Gain (Entropy reduction) or Gini Impurity. Random Forests aggregate decision trees using Bagging (Bootstrap Aggregating) to reduce variance without increasing bias.",
    "Support Vector Machines (SVM) find the optimal hyper-plane maximizing the margin between decision boundaries. Non-linear boundaries are constructed using Kernel functions (RBF, Polynomial) which implicitly map data into high-dimensional feature spaces.",
    "Deep Learning introduction: Artificial Neural Networks consist of input, hidden, and output layers. Forward propagation computes activations via non-linear functions (ReLU, Sigmoid), while Backpropagation uses gradient descent and chain rule to update weights.",
  ],
  "Cloud Computing": [
    "Cloud Computing Service Models: Infrastructure as a Service (IaaS) provides virtualized compute, storage, and networking (e.g. AWS EC2). Platform as a Service (PaaS) abstracts OS and runtime management (e.g. GCP App Engine). Software as a Service (SaaS) delivers full applications over web (e.g. Google Workspace).",
    "Containerization vs Virtualization: Virtual Machines run full guest OS instances on top of a hypervisor. Docker containers share the host kernel, isolating processes using Linux namespaces and cgroups, resulting in sub-second startup and minimal resource overhead.",
    "Serverless Computing (FaaS) allows developers to run event-driven functions (e.g. AWS Lambda) without provisioning servers. Billing is strictly based on execution duration (milliseconds) and invocation count.",
  ],
  "Distributed Systems": [
    "The CAP Theorem states that a distributed data store can simultaneously provide at most two out of three guarantees: Consistency (every read receives the latest write), Availability (every request receives a non-error response), and Partition Tolerance (system operates despite network breaks).",
    "Raft Consensus Algorithm ensures state machine replication across a cluster. It elects a single Leader using randomized election timeouts, replicates log entries sequentially to Followers, and commits entries once majority quorum (N/2 + 1) acknowledges.",
  ],
  "Operating Systems": [
    "CPU Scheduling Algorithms: First-Come First-Served (FCFS) suffers from convoy effect. Shortest Job First (SJF) minimizes average waiting time but requires prior burst time knowledge. Round Robin (RR) uses time quanta to ensure fair CPU allocation in time-sharing environments.",
    "Virtual Memory & Page Replacement: Paging maps virtual addresses to physical frames via Page Tables. When a page fault occurs, algorithms like LRU (Least Recently Used) or FIFO replace victim pages. The Belady Anomaly shows that FIFO can increase page faults even with more frames.",
  ],
};

function computeSimilarity(query: string, content: string, strategy: RetrievalStrategy): { dense: number; bm25: number; final: number } {
  const qTerms = query.toLowerCase().split(/\s+/).filter((t) => t.length > 2);
  const cText = content.toLowerCase();

  let matches = 0;
  qTerms.forEach((t) => {
    if (cText.includes(t)) matches++;
  });

  const bm25 = Math.min(1.0, (matches / Math.max(1, qTerms.length)) * 0.95);
  // Dense similarity simulation (semantic overlap + baseline noise)
  const dense = Math.min(1.0, bm25 * 0.85 + 0.15 + (matches > 0 ? 0.2 : 0.05));

  let final = dense;
  if (strategy === "Hybrid (BM25+Dense)") {
    final = 0.5 * dense + 0.5 * bm25;
  } else if (strategy === "Code Syntax Aware") {
    final = matches > 0 ? Math.min(1.0, dense + 0.1) : dense * 0.5;
  } else if (strategy === "Multi-Doc Synthesis") {
    final = Math.min(1.0, (dense + bm25) / 1.8);
  }

  return {
    dense: Math.round(dense * 100) / 100,
    bm25: Math.round(bm25 * 100) / 100,
    final: Math.round(final * 100) / 100,
  };
}

// ─── Main Adaptive RAG Pipeline Execution ────────────────────────────────────

export async function runAdaptiveRagPipeline(
  query: string,
  subjectName: string,
  mode: RagMode,
  relevanceThreshold: number,
  approvedDocs: AppDocument[],
): Promise<RagResponse> {
  const intent = classifyIntent(query);
  const strategy = selectStrategy(intent, mode);

  const steps: PipelineStep[] = [
    { step: 1, title: "Intent Classification", detail: `Classified as "${intent}" → Strategy: ${strategy}`, status: "completed" },
    { step: 2, title: "Query Expansion & Normalization", detail: `Expanded: "${query} (${subjectName} context)"`, status: "completed" },
    { step: 3, title: "Vector & Hybrid Retrieval", detail: "Searching high-dimensional embeddings & BM25 index", status: "completed" },
    { step: 4, title: "Grounded Response & Guardrail Check", detail: "Synthesizing answer with citation verification", status: "completed" },
  ];

  // Off-topic rejection
  if (intent === "off_topic" || strategy === "Direct Rejection") {
    return {
      intent,
      strategy: "Direct Rejection",
      queryExpanded: query,
      retrievedChunks: [],
      confidenceScore: 100,
      hallucinationCheck: {
        passed: true,
        overlapScore: 1.0,
        reason: "Off-topic filter triggered. No knowledge retrieval attempted.",
      },
      answer: `I am your CSPIT CSE AI Learning Assistant. I am dedicated to helping you with your course syllabus (${subjectName} and related CSE topics). Please ask a question related to your studies!`,
      citations: [],
      followUpSuggestions: [
        `What are the core concepts in ${subjectName}?`,
        `Can you explain an important topic for ${subjectName}?`,
        `Show me exam revision notes for ${subjectName}`,
      ],
      shouldEscalate: false,
      pipelineSteps: steps,
    };
  }

  // Retrieve matching candidate chunks from mock pool + uploaded docs
  const subjectDocs = approvedDocs.filter(
    (d) => d.status === "approved"
  );

  const pool = MOCK_CHUNKS[subjectName] ?? MOCK_CHUNKS["Big Data Analytics"];
  const allCandidateChunks: RetrievedChunk[] = [];

  // Seed standard chunks for the subject
  pool.forEach((txt, idx) => {
    const scores = computeSimilarity(query, txt, strategy);
    allCandidateChunks.push({
      id: `chunk_seed_${idx}`,
      docId: `doc_seed_${idx}`,
      docName: `${subjectName} Unit ${idx + 1} Core Notes.pdf`,
      fileType: "pdf",
      subjectName,
      unit: `Unit ${idx + 1}`,
      pageNumber: (idx + 1) * 4 + 2,
      content: txt,
      similarityScore: scores.final,
      denseScore: scores.dense,
      bm25Score: scores.bm25,
    });
  });

  // Include user-uploaded approved docs
  subjectDocs.forEach((doc, idx) => {
    const txt = `[From uploaded material "${doc.name}"]: ${doc.topicTag ? `Topic: ${doc.topicTag}. ` : ""}${subjectName} course reference content covering ${doc.difficulty} difficulty material for Semester ${doc.semester}. Key concepts and structured explanations are provided.`;
    const scores = computeSimilarity(query, txt + " " + doc.name, strategy);
    allCandidateChunks.push({
      id: `chunk_uploaded_${doc.id}`,
      docId: doc.id,
      docName: doc.name,
      fileType: doc.fileType,
      subjectName,
      unit: doc.topicTag ? `Tag: ${doc.topicTag}` : `Unit ${idx + 1}`,
      pageNumber: 12,
      content: txt,
      similarityScore: scores.final,
      denseScore: scores.dense,
      bm25Score: scores.bm25,
    });
  });

  // Sort by similarity descending
  allCandidateChunks.sort((a, b) => b.similarityScore - a.similarityScore);

  // Filter by relevance threshold
  const filteredChunks = allCandidateChunks.filter((c) => c.similarityScore >= relevanceThreshold);
  const topChunks = (filteredChunks.length > 0 ? filteredChunks : allCandidateChunks).slice(0, 4);

  // Compute confidence score
  const avgSimilarity = topChunks.reduce((acc, c) => acc + c.similarityScore, 0) / Math.max(1, topChunks.length);
  const confidenceScore = Math.min(98, Math.round(avgSimilarity * 100 + 10));

  // Hallucination check
  const hallucinationPassed = avgSimilarity >= 0.45;
  const hallucinationReason = hallucinationPassed
    ? "Context overlap > 0.45 threshold. High grounding confidence."
    : "Low context overlap detected (< 0.45 threshold). Answer synthesized with disclaimer.";

  // Synthesize answer text with citations
  let answer = "";
  if (topChunks.length > 0 && topChunks[0].similarityScore > 0.3) {
    const top = topChunks[0];
    answer = `Based on your course materials in **${subjectName}** [1]:\n\n${top.content}\n\nKey takeaways:\n• **Core Concept**: ${top.unit} provides the theoretical framework for solving this problem efficiently.\n• **Application**: In practical systems, this ensures scalability, fault tolerance, and optimal resource utilization.`;
    if (topChunks.length > 1) {
      answer += `\n\nAdditionally, according to **${topChunks[1].docName}** [2]:\n"${topChunks[1].content.slice(0, 180)}..."`;
    }
  } else {
    answer = `Here is an explanation for **"${query}"** based on standard ${subjectName} principles:\n\nThe topic involves understanding the underlying system architecture, operational constraints, and algorithmic trade-offs. Note that matching chunks in the current uploaded knowledge base had a lower similarity score; please verify against your lecture slides.`;
  }

  // Citations
  const citations = topChunks.map((c, i) => ({
    id: `cit_${i + 1}`,
    docName: c.docName,
    page: c.pageNumber,
    unit: c.unit,
    chunkContent: c.content,
    similarity: c.similarityScore,
  }));

  // Follow-up recommendations
  const followUpSuggestions = [
    `Can you give a numerical example of ${query.slice(0, 20)}?`,
    `What are the advantages and disadvantages of this approach?`,
    `How is this asked in end-semester exams?`,
  ];

  const shouldEscalate = confidenceScore < 75 || !hallucinationPassed;

  return {
    intent,
    strategy,
    queryExpanded: `${query} [subject:${subjectName}, mode:${mode}]`,
    retrievedChunks: topChunks,
    confidenceScore,
    hallucinationCheck: {
      passed: hallucinationPassed,
      overlapScore: Math.round(avgSimilarity * 100) / 100,
      reason: hallucinationReason,
    },
    answer,
    citations,
    followUpSuggestions,
    shouldEscalate,
    pipelineSteps: steps,
  };
}
